import { useMemo } from "react";
import { useAuthStore } from "../store/authStore";
import { useDataStore } from "../store/dataStore";
import { revenueByBusiness, summarizeRevenue } from "../lib/revenue";

const money = (value: number) => `MYR ${Math.round(value).toLocaleString()}`;
export function Analytics() {
  const workspace = useAuthStore(s => s.workspace); const store = useDataStore();
  const events = store.revenueEvents.filter(event => event.workspaceId === workspace?.id);
  const rows = useMemo(() => revenueByBusiness(events), [events]); const totals = useMemo(() => summarizeRevenue(events), [events]);
  const leads = store.leads.filter(row => row.workspaceId === workspace?.id); const opportunities = store.opportunities.filter(row => row.workspaceId === workspace?.id);
  return <section className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Command Center</p><h1 className="mt-1 text-2xl font-bold">Business Performance</h1><p className="mt-1 text-sm text-slate-500">Comparable financial measures, with domain records preserved separately.</p></div><div className="grid gap-3 sm:grid-cols-4"><Metric label="Collected" value={money(totals.collected)}/><Metric label="Booked" value={money(totals.booked)}/><Metric label="Expected" value={money(totals.expected)}/><Metric label="Estimated profit" value={money(totals.profit)}/></div><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Business</th><th className="px-4 py-3">Collected</th><th className="px-4 py-3">Booked</th><th className="px-4 py-3">Expected</th><th className="px-4 py-3">Profit</th><th className="px-4 py-3">Attention</th></tr></thead><tbody>{rows.map(row => <tr key={row.businessUnit} className="border-t"><td className="px-4 py-3 font-bold">{row.businessUnit}</td><td className="px-4 py-3">{money(row.collected)}</td><td className="px-4 py-3">{money(row.booked)}</td><td className="px-4 py-3">{money(row.expected)}</td><td className="px-4 py-3 text-emerald-700">{money(row.profit)}</td><td className="px-4 py-3 text-slate-500">{row.excludedForeignCurrencyEvents ? `${row.excludedForeignCurrencyEvents} FX rate missing` : "—"}</td></tr>)}</tbody></table></div><div className="grid gap-3 sm:grid-cols-3"><Metric label="WAAS leads" value={leads.length.toLocaleString()}/><Metric label="Open opportunities" value={opportunities.filter(row => !["won", "lost"].includes(row.stage.toLowerCase())).length.toLocaleString()}/><Metric label="Revenue events" value={events.length.toLocaleString()}/></div><p className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs text-slate-600">Growth, ROI, conversion and revenue per owner hour are intentionally omitted until the required historical and time-tracking data exists.</p></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>; }
