import { FormEvent, useState } from "react";
import { useAuthStore } from "../store/authStore";
import { useDataStore } from "../store/dataStore";
import { AffiliateRecord, EtsyRecord } from "../types";

export function BusinessHub() {
  const workspace = useAuthStore(s => s.workspace); const { affiliateRecords, etsyRecords, addAffiliateRecord, addEtsyRecord } = useDataStore();
  const [tab, setTab] = useState<"affiliate" | "etsy">("affiliate"); const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [value, setValue] = useState(""); const [kind, setKind] = useState<AffiliateRecord["kind"]>("program"); const [etsyKind, setEtsyKind] = useState<EtsyRecord["kind"]>("listing"); const [saving, setSaving] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); if (!workspace || !name.trim()) return; setSaving(true); try { if (tab === "affiliate") await addAffiliateRecord({ workspaceId: workspace.id, kind, name: name.trim(), status: "draft", value: value ? Number(value) : undefined, url: url || undefined }); else await addEtsyRecord({ workspaceId: workspace.id, kind: etsyKind, name: name.trim(), status: etsyKind === "listing" ? "draft" : "pending", revenue: value ? Number(value) : undefined, externalId: url || undefined }); setName(""); setUrl(""); setValue(""); } finally { setSaving(false); } }
  const affiliates = affiliateRecords.filter(r => r.workspaceId === workspace?.id); const etsy = etsyRecords.filter(r => r.workspaceId === workspace?.id);
  return <section className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Businesses</p><h1 className="mt-1 text-2xl font-bold">Growth Operations</h1><p className="mt-1 text-sm text-slate-500">Manage affiliate assets and Etsy/POD work without mixing them into WAAS or Amway data.</p></div><div className="flex gap-5 border-b border-slate-200"><button onClick={() => setTab("affiliate")} className={`border-b-2 pb-3 text-sm font-semibold ${tab === "affiliate" ? "border-indigo-600 text-indigo-700" : "border-transparent text-slate-500"}`}>Affiliate Operations</button><button onClick={() => setTab("etsy")} className={`border-b-2 pb-3 text-sm font-semibold ${tab === "etsy" ? "border-indigo-600 text-indigo-700" : "border-transparent text-slate-500"}`}>Etsy / POD</button></div><form onSubmit={submit} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-4"><input required value={name} onChange={e => setName(e.target.value)} placeholder={tab === "affiliate" ? "Program, link or lead magnet" : "Listing or order name"} className="rounded-lg border px-3 py-2 text-sm" />{tab === "affiliate" ? <select value={kind} onChange={e => setKind(e.target.value as AffiliateRecord["kind"])} className="rounded-lg border px-3 py-2 text-sm"><option value="program">Program</option><option value="link">Tracking link</option><option value="commission">Commission</option><option value="lead_magnet">Lead magnet</option></select> : <select value={etsyKind} onChange={e => setEtsyKind(e.target.value as EtsyRecord["kind"])} className="rounded-lg border px-3 py-2 text-sm"><option value="listing">Listing</option><option value="order">Order</option></select>}<input value={url} onChange={e => setUrl(e.target.value)} placeholder={tab === "affiliate" ? "Destination URL" : "SKU / external ID"} className="rounded-lg border px-3 py-2 text-sm" /><input type="number" min="0" value={value} onChange={e => setValue(e.target.value)} placeholder={tab === "affiliate" ? "Commission value" : "Price / revenue"} className="rounded-lg border px-3 py-2 text-sm" /><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white sm:col-span-4">{saving ? "Saving…" : `Save ${tab === "affiliate" ? "affiliate record" : etsyKind}`}</button></form>{tab === "affiliate" ? <RecordTable headers={["Type", "Name", "Status", "Value"]} rows={affiliates.map(r => [r.kind.replace("_", " "), r.name, r.status, r.value ? `MYR ${r.value.toLocaleString()}` : "—"])} empty="No affiliate records yet." /> : <RecordTable headers={["Type", "Name", "Status", "Revenue", "External ID"]} rows={etsy.map(r => [r.kind, r.name, r.status, r.revenue ? `MYR ${r.revenue.toLocaleString()}` : "—", r.externalId || "—"])} empty="No Etsy/POD records yet." />}</section>;
}
function RecordTable({ headers, rows, empty }: { headers: string[]; rows: string[][]; empty: string }) { return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{headers.map(h => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, i) => <tr key={i} className="border-t border-slate-100">{row.map((cell, j) => <td key={j} className="px-4 py-3 capitalize">{cell}</td>)}</tr>) : <tr><td colSpan={headers.length} className="px-4 py-12 text-center text-slate-500">{empty}</td></tr>}</tbody></table></div>; }
