import { useEffect, useState } from "react";
import { useAuthStore } from "../store/authStore";
import { supabase } from "../supabase";

type Brief = { date: string; content: string; source: "deterministic" | "gemini"; model?: string; cached: boolean; createdAt: string };
export function DailyBrief() {
  const workspace = useAuthStore(s => s.workspace); const [brief, setBrief] = useState<Brief | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function generate(force = false) { if (!workspace) return; setLoading(true); setError(""); try { const { data } = await supabase.auth.getSession(); if (!data.session?.access_token) throw new Error("Sign in again to generate the brief"); const response = await fetch("/api/ai/daily-brief", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${data.session.access_token}` }, body: JSON.stringify({ workspaceId: workspace.id, force }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Brief generation failed"); setBrief(result); } catch (requestError: any) { setError(requestError.message); } finally { setLoading(false); } }
  useEffect(() => { void generate(false); }, [workspace?.id]);
  return <section className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Command Center</p><h1 className="mt-1 text-2xl font-bold">Daily CEO Brief</h1><p className="mt-1 text-sm text-slate-500">Evidence-only operating guidance. Missing data is stated, never fabricated.</p></div><button disabled={loading} onClick={() => void generate(true)} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{loading ? "Generating…" : "Regenerate from live data"}</button></div>{error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!brief && loading ? <div className="rounded-xl border border-slate-200 bg-white p-12 text-center text-sm text-slate-500">Building today’s evidence pack…</div> : brief ? <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-5 flex flex-wrap justify-between gap-2 border-b border-slate-100 pb-4"><div><p className="text-xs font-bold uppercase text-slate-500">Generated {new Date(brief.createdAt).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">Source: {brief.source === "gemini" ? `Gemini · ${brief.model}` : "Deterministic data engine"}{brief.cached ? " · cached today" : ""}</p></div></div><div className="whitespace-pre-wrap text-sm leading-7 text-slate-800">{brief.content}</div></article> : null}</section>;
}
