import { FormEvent, useMemo, useState } from "react";
import { useAuthStore } from "../store/authStore";
import { useDataStore } from "../store/dataStore";
import { EtsyProductStatus } from "../types";
import { etsyProfit } from "../lib/etsy";
import { Link } from "../lib/router";

const stages: EtsyProductStatus[] = ["IDEA", "RESEARCH", "DESIGN", "SEO", "CREATIVE", "REVIEW", "APPROVED", "DRAFT", "PUBLISHED", "OPTIMIZING", "PAUSED", "ARCHIVED"];
export function EtsyOperations() {
  const workspace = useAuthStore(s => s.workspace); const { etsyProducts, etsyRecords, printifyRecords, addEtsyProduct, updateEtsyProduct } = useDataStore();
  const products = etsyProducts.filter(product => product.workspaceId === workspace?.id); const orders = etsyRecords.filter(record => record.workspaceId === workspace?.id && record.kind === "order");
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ internalName: "", productType: "", niche: "", audience: "", occasion: "", designConcept: "", personalization: "", price: "", productionCost: "", etsyFees: "" });
  const totals = useMemo(() => products.reduce((acc, product) => { const result = etsyProfit(product); if (result.known) { acc.known++; acc.profit += result.profit; } else acc.unknown++; return acc; }, { known: 0, unknown: 0, profit: 0 }), [products]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!workspace || !form.internalName.trim() || Number(form.price) <= 0) return; setSaving(true); try { await addEtsyProduct({ workspaceId: workspace.id, internalName: form.internalName.trim(), status: "IDEA", productType: form.productType.trim(), niche: form.niche.trim(), audience: form.audience.trim(), occasion: form.occasion.trim() || undefined, designConcept: form.designConcept.trim(), personalization: form.personalization.trim() || undefined, currency: "MYR", price: Number(form.price), productionCost: form.productionCost ? Number(form.productionCost) : undefined, etsyFees: form.etsyFees ? Number(form.etsyFees) : undefined }); setForm({ internalName: "", productType: "", niche: "", audience: "", occasion: "", designConcept: "", personalization: "", price: "", productionCost: "", etsyFees: "" }); setOpen(false); } finally { setSaving(false); } }
  async function advance(id: string, status: EtsyProductStatus) { const current = stages.indexOf(status); if (current < 0 || current >= stages.indexOf("PUBLISHED")) return; const next = stages[current + 1]; await updateEtsyProduct(id, { status: next, approvedAt: next === "APPROVED" ? new Date().toISOString() : undefined, publishedAt: next === "PUBLISHED" ? new Date().toISOString() : undefined }); }
  return <section className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Etsy business</p><h1 className="mt-1 text-2xl font-bold">Etsy Automation & Growth</h1><p className="mt-1 text-sm text-slate-500">Internal product pipeline, economics and human approvals.</p></div><div className="flex gap-2"><Link to="/businesses" className="rounded-lg border px-4 py-2 text-sm font-semibold">Connections & sync</Link><button onClick={() => setOpen(v => !v)} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Create product</button></div></div><div className="grid gap-3 sm:grid-cols-4"><Metric label="Internal products" value={products.length.toLocaleString()}/><Metric label="Imported Etsy orders" value={orders.length.toLocaleString()}/><Metric label="Printify records" value={printifyRecords.length.toLocaleString()}/><Metric label="Known profit / order" value={totals.known ? `MYR ${totals.profit.toLocaleString()}` : "Costs missing"}/></div>
    {open && <form onSubmit={submit} className="grid gap-3 rounded-xl border border-indigo-100 bg-indigo-50/50 p-4 md:grid-cols-3"><input required value={form.internalName} onChange={e => setForm({ ...form, internalName: e.target.value })} placeholder="Internal product name" className="rounded-lg border px-3 py-2 text-sm"/><input required value={form.productType} onChange={e => setForm({ ...form, productType: e.target.value })} placeholder="Product type" className="rounded-lg border px-3 py-2 text-sm"/><input required value={form.niche} onChange={e => setForm({ ...form, niche: e.target.value })} placeholder="Niche" className="rounded-lg border px-3 py-2 text-sm"/><input required value={form.audience} onChange={e => setForm({ ...form, audience: e.target.value })} placeholder="Audience" className="rounded-lg border px-3 py-2 text-sm"/><input value={form.occasion} onChange={e => setForm({ ...form, occasion: e.target.value })} placeholder="Occasion (optional)" className="rounded-lg border px-3 py-2 text-sm"/><input required value={form.designConcept} onChange={e => setForm({ ...form, designConcept: e.target.value })} placeholder="Design concept" className="rounded-lg border px-3 py-2 text-sm"/><input value={form.personalization} onChange={e => setForm({ ...form, personalization: e.target.value })} placeholder="Personalization" className="rounded-lg border px-3 py-2 text-sm"/><input required type="number" min="0.01" step="0.01" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} placeholder="Selling price MYR" className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" step="0.01" value={form.productionCost} onChange={e => setForm({ ...form, productionCost: e.target.value })} placeholder="Production cost" className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" step="0.01" value={form.etsyFees} onChange={e => setForm({ ...form, etsyFees: e.target.value })} placeholder="Etsy fees" className="rounded-lg border px-3 py-2 text-sm"/><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white md:col-span-2">{saving ? "Saving…" : "Save as idea"}</button></form>}
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-6">{stages.map(stage => <div key={stage} className="rounded-lg border border-slate-200 bg-white p-3"><p className="text-[10px] font-bold text-slate-500">{stage}</p><p className="mt-1 text-xl font-bold">{products.filter(product => product.status === stage).length}</p></div>)}</div>
    <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Profit</th><th className="px-4 py-3">Margin</th><th className="px-4 py-3">Approval action</th></tr></thead><tbody>{products.length ? products.map(product => { const result = etsyProfit(product); return <tr key={product.id} className="border-t"><td className="px-4 py-3"><p className="font-bold">{product.internalName}</p><p className="text-xs text-slate-500">{product.niche} · {product.audience}</p></td><td className="px-4 py-3 font-semibold">{product.status}</td><td className="px-4 py-3">{product.currency} {product.price.toLocaleString()}</td><td className="px-4 py-3">{result.known ? `${product.currency} ${result.profit.toLocaleString()}` : "Costs incomplete"}</td><td className="px-4 py-3">{result.known ? `${result.margin.toFixed(1)}%` : "—"}</td><td className="px-4 py-3">{stages.indexOf(product.status) < stages.indexOf("PUBLISHED") ? <button onClick={() => void advance(product.id, product.status)} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white">Approve → {stages[stages.indexOf(product.status) + 1]}</button> : <span className="text-xs text-slate-500">Managed after publish</span>}</td></tr>; }) : <tr><td colSpan={6} className="px-4 py-12 text-center text-slate-500">Create the first product idea. Publishing remains a human approval step.</td></tr>}</tbody></table></div>{totals.unknown > 0 && <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">{totals.unknown} product(s) have incomplete production cost or Etsy fee data, so profit is not calculated.</p>}</section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-[11px] font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>; }
