import { FormEvent, useMemo, useState } from "react";
import { useAuthStore } from "../store/authStore";
import { useDataStore } from "../store/dataStore";
import { BusinessUnit, MoneyTask } from "../types";

const units: BusinessUnit[] = ["WAAS", "ETSY", "AFFILIATE", "AMWAY"];
const expectedImpact = (task: MoneyTask) => task.estimatedRevenueImpact === undefined || task.probability === undefined ? null : task.estimatedRevenueImpact * task.probability / 100;

export function MoneyTasks() {
  const workspace = useAuthStore(s => s.workspace); const user = useAuthStore(s => s.user);
  const { moneyTasks, addMoneyTask, updateMoneyTask } = useDataStore();
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ businessUnit: "WAAS" as BusinessUnit, title: "", reason: "", priority: "high" as MoneyTask["priority"], impact: "", probability: "", dueDate: "", recommendedAction: "" });
  const tasks = useMemo(() => moneyTasks.filter(t => t.workspaceId === workspace?.id && !["completed", "dismissed"].includes(t.status)).sort((a, b) => {
    const aImpact = expectedImpact(a); const bImpact = expectedImpact(b);
    if (aImpact !== null || bImpact !== null) return (bImpact ?? -1) - (aImpact ?? -1);
    return ["critical", "high", "medium", "low"].indexOf(a.priority) - ["critical", "high", "medium", "low"].indexOf(b.priority);
  }), [moneyTasks, workspace?.id]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!workspace || !user || !form.title.trim() || !form.recommendedAction.trim()) return; setSaving(true); try { await addMoneyTask({ workspaceId: workspace.id, businessUnit: form.businessUnit, title: form.title.trim(), reason: form.reason.trim(), priority: form.priority, estimatedRevenueImpact: form.impact ? Number(form.impact) : undefined, probability: form.probability ? Number(form.probability) : undefined, dueDate: form.dueDate || undefined, status: "open", recommendedAction: form.recommendedAction.trim(), source: "user", createdBy: user.id }); setForm({ ...form, title: "", reason: "", impact: "", probability: "", dueDate: "", recommendedAction: "" }); setOpen(false); } finally { setSaving(false); } }
  return <section className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">Command Center</p><h1 className="mt-1 text-2xl font-bold">Money Tasks</h1><p className="mt-1 text-sm text-slate-500">Rank work by evidence-backed expected financial impact.</p></div><button onClick={() => setOpen(v => !v)} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Add money task</button></div>
    {open && <form onSubmit={submit} className="grid gap-3 rounded-xl border border-indigo-100 bg-indigo-50/50 p-4 md:grid-cols-3"><select value={form.businessUnit} onChange={e => setForm({ ...form, businessUnit: e.target.value as BusinessUnit })} className="rounded-lg border px-3 py-2 text-sm">{units.map(unit => <option key={unit}>{unit}</option>)}</select><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value as MoneyTask["priority"] })} className="rounded-lg border px-3 py-2 text-sm"><option>critical</option><option>high</option><option>medium</option><option>low</option></select><input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Task title" className="rounded-lg border px-3 py-2 text-sm"/><input required value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} placeholder="Why this matters" className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" value={form.impact} onChange={e => setForm({ ...form, impact: e.target.value })} placeholder="Potential MYR (optional)" className="rounded-lg border px-3 py-2 text-sm"/><input type="number" min="0" max="100" value={form.probability} onChange={e => setForm({ ...form, probability: e.target.value })} placeholder="Probability % (optional)" className="rounded-lg border px-3 py-2 text-sm"/><input type="date" value={form.dueDate} onChange={e => setForm({ ...form, dueDate: e.target.value })} className="rounded-lg border px-3 py-2 text-sm"/><input required value={form.recommendedAction} onChange={e => setForm({ ...form, recommendedAction: e.target.value })} placeholder="Exact next action" className="rounded-lg border px-3 py-2 text-sm"/><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">{saving ? "Saving…" : "Save task"}</button></form>}
    <div className="space-y-3">{tasks.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No open money tasks. Add only actions with a clear commercial reason.</div> : tasks.map((task, index) => { const impact = expectedImpact(task); return <article key={task.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-slate-900">{task.title}</h2><span className="rounded-full bg-indigo-50 px-2 py-0.5 text-[10px] font-bold text-indigo-700">{task.businessUnit}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-bold uppercase text-slate-600">{task.priority}</span></div><p className="mt-1 text-sm text-slate-600">{task.reason}</p><p className="mt-2 text-sm font-semibold text-slate-900">Next: {task.recommendedAction}</p><div className="mt-2 flex flex-wrap gap-4 text-xs text-slate-500"><span>Potential: {task.estimatedRevenueImpact === undefined ? "Not estimated" : `MYR ${task.estimatedRevenueImpact.toLocaleString()}`}</span><span>Probability: {task.probability === undefined ? "Not estimated" : `${task.probability}%`}</span><span>Expected impact: {impact === null ? "Not calculated" : `MYR ${impact.toLocaleString()}`}</span>{task.dueDate && <span>Due: {task.dueDate}</span>}</div></div><div className="flex gap-2"><button onClick={() => void updateMoneyTask(task.id, { status: "in_progress" })} className="rounded-lg border px-3 py-2 text-xs font-semibold">Start</button><button onClick={() => void updateMoneyTask(task.id, { status: "completed" })} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Complete</button></div></div></article>; })}</div>
  </section>;
}
