import { useEffect, useState } from "react";
import { Loader2, Send } from "lucide-react";

export function WaasPortal() {
  const query = new URLSearchParams(window.location.search); const orderId = query.get("order") || ""; const token = query.get("token") || "";
  const [data, setData] = useState<any>(null); const [error, setError] = useState(""); const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!orderId || !token) { setError("This portal link is incomplete."); return; } fetch(`/api/portal/orders/${encodeURIComponent(orderId)}?token=${encodeURIComponent(token)}`).then(async r => { const body = await r.json(); if (!r.ok) throw new Error(body.error || "Portal unavailable"); return body; }).then(setData).catch(e => setError(e instanceof Error ? e.message : "Portal unavailable")); }, [orderId, token]);
  const createTicket = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const response = await fetch(`/api/portal/orders/${encodeURIComponent(orderId)}/tickets?token=${encodeURIComponent(token)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject, description, category: "general", priority: "normal" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Ticket could not be created"); setData((previous: any) => ({ ...previous, tickets: [body.ticket, ...(previous.tickets || [])] })); setSubject(""); setDescription(""); } catch (e) { setError(e instanceof Error ? e.message : "Ticket could not be created"); } finally { setSaving(false); } };
  if (error) return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><div className="max-w-md rounded-2xl border bg-white p-8 text-center shadow"><h1 className="text-2xl font-bold">Customer portal unavailable</h1><p className="mt-3 text-slate-600">{error}</p></div></main>;
  if (!data) return <main className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="h-6 w-6 animate-spin text-indigo-600" /></main>;
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-950 sm:p-10"><div className="mx-auto max-w-4xl space-y-6"><header><p className="text-sm font-bold uppercase tracking-[.18em] text-indigo-600">BennieTay customer portal</p><h1 className="mt-2 text-3xl font-black">Your website project</h1></header><section className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border bg-white p-5"><p className="text-xs uppercase text-slate-500">Order status</p><strong className="mt-2 block text-xl capitalize">{String(data.order.status).replaceAll("_", " ")}</strong></div><div className="rounded-xl border bg-white p-5"><p className="text-xs uppercase text-slate-500">Product</p><strong className="mt-2 block text-xl capitalize">{data.order.productType} website</strong></div><div className="rounded-xl border bg-white p-5"><p className="text-xs uppercase text-slate-500">Website</p><strong className="mt-2 block text-xl">{data.website?.domain || "Preparing"}</strong></div></section><section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Need help?</h2><form onSubmit={createTicket} className="mt-4 space-y-3"><input required placeholder="Subject" className="w-full rounded-lg border px-3 py-3" value={subject} onChange={e => setSubject(e.target.value)} /><textarea required placeholder="Describe what you need" className="min-h-28 w-full rounded-lg border px-3 py-3" value={description} onChange={e => setDescription(e.target.value)} /><button disabled={saving} className="inline-flex items-center rounded-lg bg-indigo-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}Create support ticket</button></form></section><section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Recent tickets</h2><div className="mt-4 space-y-2">{data.tickets?.length ? data.tickets.map((ticket: any) => <div key={ticket.id} className="rounded-lg bg-slate-50 p-3"><strong>{ticket.ticketNumber || ticket.subject}</strong><span className="ml-2 text-sm capitalize text-slate-500">{ticket.status}</span><p className="mt-1 text-sm text-slate-600">{ticket.description}</p></div>) : <p className="text-sm text-slate-500">No tickets yet.</p>}</div></section></div></main>;
}
