import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { useAuthStore } from "../store/authStore";
import { useDataStore } from "../store/dataStore";
import { WaasOrderStatus, WaasProductType, WaasTicketStatus } from "../types";

type Tab = "overview" | "orders" | "websites" | "deployments" | "templates" | "support" | "plans";
const orderStatuses: WaasOrderStatus[] = ["pending_payment", "paid", "awaiting_onboarding", "onboarding_in_progress", "ready_for_deployment", "deploying", "review_required", "customer_review", "approved", "live", "cancelled", "failed"];
const ticketStatuses: WaasTicketStatus[] = ["new", "open", "in_progress", "waiting_for_customer", "resolved", "closed"];

export function WaasOperations() {
  const workspace = useAuthStore(s => s.workspace);
  const { waasPlans, waasOrders, waasWebsites, waasDeployments, waasTemplates, waasSupportTickets, addWaasPlan, addWaasOrder, updateWaasOrder, addWaasWebsite, updateWaasWebsite, addWaasDeployment, updateWaasDeployment, addWaasTemplate, addWaasTicket, updateWaasTicket } = useDataStore();
  const [tab, setTab] = useState<Tab>("overview");
  const [showOrder, setShowOrder] = useState(false);
  const [showTicket, setShowTicket] = useState(false);
  const [saving, setSaving] = useState(false);
  const seededWorkspace = useRef<string | null>(null);
  const activeWorkspaceId = workspace?.id || "";
  useEffect(() => {
    if (!activeWorkspaceId || seededWorkspace.current === activeWorkspaceId || waasPlans.length || waasTemplates.length) return;
    seededWorkspace.current = activeWorkspaceId;
    void Promise.all([
      addWaasPlan({ workspaceId: activeWorkspaceId, name: "Launch Website", productType: "launch", setupFee: 0, recurringFee: 0, billingInterval: "month", pagesIncluded: 1, updateAllowance: 2, supportSlaHours: 48, features: ["Lead-generation landing page", "Managed hosting", "SSL and backups"], currency: "MYR", active: true }),
      addWaasPlan({ workspaceId: activeWorkspaceId, name: "Business Website", productType: "business", setupFee: 0, recurringFee: 0, billingInterval: "month", pagesIncluded: 5, updateAllowance: 4, supportSlaHours: 24, features: ["Five-page website", "Managed hosting", "CRM lead capture"], currency: "MYR", active: true }),
      ...["Home Services", "Professional Services", "Beauty & Wellness", "Healthcare", "F&B", "Automotive", "Education", "B2B / Industrial"].flatMap(niche => ["launch", "business"].map(productType => addWaasTemplate({ workspaceId: activeWorkspaceId, name: `${niche} ${productType === "launch" ? "Launch" : "Business"} Modern`, productType: productType as WaasProductType, niche, style: "modern", version: "1.0.0", status: "active", themePackageId: `bennietay-${productType}-modern`, configuration: { hero: "H02", services: "S03", about: "A01", testimonials: "T02", faq: "F01", cta: "C03", contact: "CT01" }, supportedSections: ["hero", "services", "about", "testimonials", "faq", "cta", "contact"], changelog: "Initial managed template library" })))
    ]).catch(error => console.error("WAAS defaults could not be seeded", error));
  }, [activeWorkspaceId, waasPlans.length, waasTemplates.length, addWaasPlan, addWaasTemplate]);
  const metrics = useMemo(() => ({
    newOrders: waasOrders.filter(o => ["paid", "awaiting_onboarding"].includes(o.status)).length,
    onboarding: waasOrders.filter(o => ["awaiting_onboarding", "onboarding_in_progress"].includes(o.status)).length,
    deploy: waasOrders.filter(o => ["ready_for_deployment", "deploying", "review_required"].includes(o.status)).length,
    live: waasWebsites.filter(site => site.status === "live").length,
    failed: waasDeployments.filter(d => d.status === "failed").length,
    tickets: waasSupportTickets.filter(t => !["resolved", "closed"].includes(t.status)).length,
  }), [waasOrders, waasWebsites, waasDeployments, waasSupportTickets]);

  async function createOrder(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!activeWorkspaceId) return; setSaving(true);
    const form = new FormData(event.currentTarget); const productType = String(form.get("productType")) as WaasProductType; const customerName = String(form.get("customerName") || "").trim();
    try { await addWaasOrder({ workspaceId: activeWorkspaceId, customerName, customerEmail: String(form.get("email") || "").trim() || undefined, productType, planId: String(form.get("planId") || "") || undefined, niche: String(form.get("niche") || "Home Services"), style: String(form.get("style") || "modern"), status: "paid", paymentStatus: "paid" }); setShowOrder(false); event.currentTarget.reset(); } finally { setSaving(false); }
  }
  async function createTicket(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!activeWorkspaceId) return; setSaving(true); const form = new FormData(event.currentTarget); try { await addWaasTicket({ workspaceId: activeWorkspaceId, ticketNumber: `WAAS-${Date.now().toString().slice(-6)}`, subject: String(form.get("subject") || "").trim(), description: String(form.get("description") || "").trim(), category: "general", priority: String(form.get("priority") || "normal") as any, status: "new", source: "admin" }); setShowTicket(false); event.currentTarget.reset(); } finally { setSaving(false); } }
  async function startDeployment(orderId: string) { if (!activeWorkspaceId) return; const existing = waasDeployments.find(d => d.orderId === orderId); if (existing) { await updateWaasDeployment(existing.id, { status: "running", currentStep: "validate_order", startedAt: new Date().toISOString() }); } else await addWaasDeployment({ workspaceId: activeWorkspaceId, orderId, status: "queued", provider: "mock", currentStep: "validate_order" }); await updateWaasOrder(orderId, { status: "deploying" }); }

  return <section className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600">WAAS operations</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Managed WordPress control center</h1><p className="mt-1 text-sm text-slate-500">Orders, onboarding, templates, deployments and support for the standalone website business.</p></div><div className="flex gap-2"><button onClick={() => setShowTicket(true)} className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold">New ticket</button><button onClick={() => setShowOrder(true)} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">New order</button></div></header>
    <nav className="flex gap-2 overflow-x-auto border-b border-slate-200 pb-px">{(["overview", "orders", "websites", "deployments", "templates", "support", "plans"] as Tab[]).map(item => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-2 pb-3 text-sm font-semibold capitalize ${tab === item ? "border-indigo-600 text-indigo-700" : "border-transparent text-slate-500"}`}>{item}</button>)}</nav>
    {tab === "overview" && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["New orders", metrics.newOrders], ["Onboarding", metrics.onboarding], ["Deployment queue", metrics.deploy], ["Live websites", metrics.live], ["Failed deploys", metrics.failed], ["Open tickets", metrics.tickets]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div>)}</div><div className="grid gap-4 lg:grid-cols-2"><Panel title="Recent orders">{waasOrders.slice(-8).reverse().map(order => <div key={order.id} className="flex items-center justify-between border-b border-slate-100 py-3 text-sm"><div><p className="font-semibold">{order.customerName}</p><p className="text-xs text-slate-500">{order.productType} · {order.niche || "Niche pending"}</p></div><Status value={order.status}/></div>)}{!waasOrders.length && <Empty text="No WAAS orders yet."/>}</Panel><Panel title="Recent deployments">{waasDeployments.slice(-8).reverse().map(deployment => <div key={deployment.id} className="flex items-center justify-between border-b border-slate-100 py-3 text-sm"><div><p className="font-semibold">{deployment.currentStep || "Deployment"}</p><p className="text-xs text-slate-500">{deployment.provider} · {deployment.id}</p></div><Status value={deployment.status}/></div>)}{!waasDeployments.length && <Empty text="No deployments yet."/>}</Panel></div></>}
    {tab === "orders" && <Panel title="Orders"><Table headers={["Customer", "Product", "Niche", "Status", "Action"]}>{waasOrders.map(order => <tr key={order.id} className="border-t"><td className="px-3 py-3 font-semibold">{order.customerName}</td><td className="px-3 py-3 capitalize">{order.productType}</td><td className="px-3 py-3">{order.niche || "—"}</td><td className="px-3 py-3"><Status value={order.status}/></td><td className="px-3 py-3">{["paid", "ready_for_deployment", "failed"].includes(order.status) && <button onClick={() => void startDeployment(order.id)} className="text-xs font-semibold text-indigo-700">{order.status === "failed" ? "Retry" : "Start deployment"}</button>}</td></tr>)}</Table></Panel>}
    {tab === "websites" && <Panel title="Websites"><Table headers={["Domain", "Customer", "Product", "Niche", "Status", "Health"]}>{waasWebsites.map(site => <tr key={site.id} className="border-t"><td className="px-3 py-3 font-semibold">{site.liveUrl || site.temporaryUrl || "Not provisioned"}</td><td className="px-3 py-3">{site.customerId || "—"}</td><td className="px-3 py-3 capitalize">{site.productType}</td><td className="px-3 py-3">{site.niche || "—"}</td><td className="px-3 py-3"><Status value={site.status}/></td><td className="px-3 py-3 text-xs text-slate-500">{site.lastHealthCheck || "Not checked"}</td></tr>)}</Table></Panel>}
    {tab === "deployments" && <Panel title="Deployment jobs"><Table headers={["Job", "Provider", "Step", "Status", "Action"]}>{waasDeployments.map(job => <tr key={job.id} className="border-t"><td className="px-3 py-3 font-mono text-xs">{job.id}</td><td className="px-3 py-3 capitalize">{job.provider}</td><td className="px-3 py-3">{job.currentStep || "Queued"}</td><td className="px-3 py-3"><Status value={job.status}/></td><td className="px-3 py-3">{job.status === "failed" && <button onClick={() => void updateWaasDeployment(job.id, { status: "queued", errorMessage: undefined })} className="text-xs font-semibold text-indigo-700">Retry</button>}</td></tr>)}</Table></Panel>}
    {tab === "templates" && <Panel title="Template library"><Table headers={["Name", "Product", "Niche", "Style", "Version", "Status"]}>{waasTemplates.map(template => <tr key={template.id} className="border-t"><td className="px-3 py-3 font-semibold">{template.name}</td><td className="px-3 py-3 capitalize">{template.productType}</td><td className="px-3 py-3">{template.niche}</td><td className="px-3 py-3 capitalize">{template.style}</td><td className="px-3 py-3">{template.version}</td><td className="px-3 py-3"><Status value={template.status}/></td></tr>)}</Table>{!waasTemplates.length && <Empty text="No templates configured. Add records through the secured storefront/import API."/>}</Panel>}
    {tab === "support" && <Panel title="Support tickets"><Table headers={["Ticket", "Subject", "Priority", "Status", "Action"]}>{waasSupportTickets.map(ticket => <tr key={ticket.id} className="border-t"><td className="px-3 py-3 font-mono text-xs">{ticket.ticketNumber}</td><td className="px-3 py-3 font-semibold">{ticket.subject}</td><td className="px-3 py-3 capitalize">{ticket.priority}</td><td className="px-3 py-3"><Status value={ticket.status}/></td><td className="px-3 py-3"><select value={ticket.status} onChange={e => void updateWaasTicket(ticket.id, { status: e.target.value as WaasTicketStatus })} className="rounded border px-2 py-1 text-xs">{ticketStatuses.map(status => <option key={status}>{status}</option>)}</select></td></tr>)}</Table></Panel>}
    {tab === "plans" && <Panel title="Plans"><Table headers={["Name", "Product", "Setup", "Recurring", "Updates", "Status"]}>{waasPlans.map(plan => <tr key={plan.id} className="border-t"><td className="px-3 py-3 font-semibold">{plan.name}</td><td className="px-3 py-3 capitalize">{plan.productType}</td><td className="px-3 py-3">{plan.currency} {plan.setupFee.toLocaleString()}</td><td className="px-3 py-3">{plan.currency} {plan.recurringFee.toLocaleString()}/{plan.billingInterval}</td><td className="px-3 py-3">{plan.updateAllowance}/mo</td><td className="px-3 py-3"><Status value={plan.active ? "active" : "inactive"}/></td></tr>)}</Table></Panel>}
    {showOrder && <Modal title="Create WAAS order" onClose={() => setShowOrder(false)}><form onSubmit={createOrder} className="space-y-3"><input name="customerName" required placeholder="Customer / business name" className="w-full rounded-lg border px-3 py-2 text-sm"/><input name="email" type="email" placeholder="Customer email" className="w-full rounded-lg border px-3 py-2 text-sm"/><select name="productType" className="w-full rounded-lg border px-3 py-2 text-sm"><option value="launch">Launch Website</option><option value="business">Business Website</option></select><input name="niche" placeholder="Niche (e.g. Home Services)" className="w-full rounded-lg border px-3 py-2 text-sm"/><select name="style" className="w-full rounded-lg border px-3 py-2 text-sm"><option>modern</option><option>bold</option><option>premium</option></select><select name="planId" className="w-full rounded-lg border px-3 py-2 text-sm"><option value="">Select plan later</option>{waasPlans.filter(plan => plan.active).map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select><button disabled={saving} className="w-full rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">{saving ? "Saving…" : "Create paid order"}</button></form></Modal>}
    {showTicket && <Modal title="Create support ticket" onClose={() => setShowTicket(false)}><form onSubmit={createTicket} className="space-y-3"><input name="subject" required placeholder="Subject" className="w-full rounded-lg border px-3 py-2 text-sm"/><textarea name="description" required placeholder="Describe the issue" className="min-h-28 w-full rounded-lg border px-3 py-2 text-sm"/><select name="priority" className="w-full rounded-lg border px-3 py-2 text-sm"><option>normal</option><option>high</option><option>critical</option><option>request</option></select><button disabled={saving} className="w-full rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">{saving ? "Saving…" : "Create ticket"}</button></form></Modal>}
  </section>;
}

function Panel({ title, children }: { title: string; children: ReactNode }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-3 font-bold text-slate-900">{title}</h2>{children}</div>; }
function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{headers.map(header => <th key={header} className="px-3 py-2">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Status({ value }: { value: string }) { return <span className="inline-flex rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold capitalize text-slate-700">{value.replaceAll("_", " ")}</span>; }
function Empty({ text }: { text: string }) { return <p className="rounded-lg border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">{text}</p>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><div className="w-full max-w-md rounded-xl bg-white p-5 shadow-xl"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">{title}</h2><button onClick={onClose} className="text-slate-400">×</button></div>{children}</div></div>; }
