<?php get_header(); $cta=bt_launch_value('cta','Request a quote'); $services=bt_launch_list('services',[['title'=>'Fast response','body'=>'Clear advice and a practical next step.'],['title'=>'Trusted service','body'=>'Experienced help focused on a lasting result.'],['title'=>'Easy booking','body'=>'Call, WhatsApp or send an enquiry in minutes.']]); $testimonials=bt_launch_list('testimonials',[['quote'=>'Responsive, professional and easy to work with.','name'=>'Local customer'],['quote'=>'A clear process from first contact to completion.','name'=>'Business owner']]); ?>
<header class="bt-nav"><div class="bt-nav-inner bt-wrap"><a class="bt-brand" href="#top"><?php if(has_custom_logo()){the_custom_logo();}else{bloginfo('name');} ?></a><button class="bt-menu" type="button" aria-expanded="false" aria-controls="bt-navigation">Menu</button><nav id="bt-navigation"><a href="#services">Services</a><a href="#about">About</a><a href="#reviews">Reviews</a><a href="#faq">FAQ</a><a class="bt-button" href="#contact"><?php echo esc_html($cta); ?></a></nav></div></header>
<main id="top"><section class="bt-hero"><div class="bt-wrap bt-reveal"><p class="bt-kicker"><?php echo esc_html(bt_launch_value('kicker','Trusted local experts')); ?></p><h1><?php echo esc_html(bt_launch_value('hero','Reliable service. Clear answers. A fast next step.')); ?></h1><p class="bt-lead"><?php echo esc_html(bt_launch_value('intro','Tell us what you need and get a helpful response from a real person.')); ?></p><a class="bt-button" href="#contact"><?php echo esc_html($cta); ?></a></div></section>
<section class="bt-trust"><div class="bt-wrap bt-trust-grid"><span>Responsive support</span><span>Clear communication</span><span>Local expertise</span><span>Quality workmanship</span></div></section>
<?php $stats=bt_launch_list('stats',[]); if($stats){ ?><section class="bt-section bt-stats" aria-label="Key results"><div class="bt-wrap bt-stats-grid"><?php foreach($stats as $stat){ ?><div class="bt-stat bt-reveal"><strong data-bt-counter="<?php echo esc_attr((int)($stat['value']??0)); ?>">0</strong><span><?php echo esc_html($stat['label']??''); ?></span></div><?php } ?></div></section><?php } ?>
<section id="services" class="bt-section"><div class="bt-wrap"><p class="bt-kicker">What we do</p><h2><?php echo esc_html(bt_launch_value('services_title','Services built around your needs')); ?></h2><div class="bt-grid"><?php foreach($services as $service){ ?><article class="bt-card bt-reveal"><h3><?php echo esc_html($service['title']??'Service'); ?></h3><p><?php echo esc_html($service['body']??'Ask us how we can help.'); ?></p></article><?php } ?></div></div></section>
<section class="bt-section bt-surface"><div class="bt-wrap bt-split"><div class="bt-reveal"><p class="bt-kicker">Why choose us</p><h2><?php echo esc_html(bt_launch_value('why_title','A simpler way to get the job done')); ?></h2><p><?php echo esc_html(bt_launch_value('why_body','We combine practical experience, honest communication and a straightforward process so you always know what happens next.')); ?></p></div><ul class="bt-checks bt-reveal"><li>Fast, personal response</li><li>Clear scope and expectations</li><li>Work designed around your priorities</li></ul></div></section>
<section id="about" class="bt-section"><div class="bt-wrap bt-reveal"><p class="bt-kicker">About us</p><h2><?php echo esc_html(bt_launch_value('about_title','People who care about the result')); ?></h2><p class="bt-lead"><?php echo esc_html(bt_launch_value('about_body','We help customers make confident decisions with clear advice, dependable service and attention to the details that matter.')); ?></p></div></section>
<section id="reviews" class="bt-section bt-surface"><div class="bt-wrap"><p class="bt-kicker">Customer stories</p><h2>Trusted by people like you</h2><div class="bt-slider" data-bt-slider><div class="bt-slider-track"><?php foreach($testimonials as $review){ ?><blockquote class="bt-card bt-slide bt-reveal"><p>“<?php echo esc_html($review['quote']??'Excellent service.'); ?>”</p><cite><?php echo esc_html($review['name']??'Customer'); ?></cite></blockquote><?php } ?></div><div class="bt-slider-controls" aria-label="Testimonial controls"><button type="button" data-bt-prev aria-label="Previous testimonial">←</button><button type="button" data-bt-next aria-label="Next testimonial">→</button></div></div></div></section>
<?php $gallery=bt_launch_list('gallery',[]); if($gallery){ ?><section class="bt-section"><div class="bt-wrap"><p class="bt-kicker">Our work</p><h2>Recent highlights</h2><div class="bt-gallery"><?php foreach($gallery as $image){ ?><a href="<?php echo esc_url($image['url']??''); ?>" class="bt-lightbox"><img loading="lazy" src="<?php echo esc_url($image['url']??''); ?>" alt="<?php echo esc_attr($image['alt']??'Project'); ?>"></a><?php } ?></div></div></section><?php } ?>
<section id="faq" class="bt-section"><div class="bt-wrap"><p class="bt-kicker">Questions</p><h2>Frequently asked questions</h2><details class="bt-card bt-reveal"><summary>How quickly can we get started?</summary><p>Send your enquiry and we will confirm availability and the best next step.</p></details><details class="bt-card bt-reveal"><summary>Which areas do you serve?</summary><p><?php echo esc_html(bt_launch_value('service_areas','Contact us with your location and we will confirm service availability.')); ?></p></details></div></section>
<section class="bt-cta"><div class="bt-wrap bt-reveal"><h2><?php echo esc_html(bt_launch_value('cta_title','Ready to move forward?')); ?></h2><p>Get a clear answer and a practical next step.</p><a class="bt-button bt-button-light" href="#contact"><?php echo esc_html($cta); ?></a></div></section>
<section id="contact" class="bt-section bt-surface"><div class="bt-wrap bt-split"><div><p class="bt-kicker">Contact</p><h2>Tell us how we can help</h2><p>Send the form and your enquiry will be safely recorded for follow-up.</p><?php $phone=bt_launch_value('phone',''); if($phone){ ?><p><a href="tel:<?php echo esc_attr(preg_replace('/[^0-9+]/','',$phone)); ?>"><?php echo esc_html($phone); ?></a></p><?php } ?></div><div class="bt-reveal"><?php $contact_shortcode=trim((string)bt_launch_value('contact_shortcode','[bennietay_lead_form]')); if(shortcode_exists('bennietay_lead_form')){echo do_shortcode($contact_shortcode);}else{ ?><p><a class="bt-button" href="mailto:<?php echo esc_attr(get_option('admin_email')); ?>?subject=<?php echo rawurlencode('Website enquiry'); ?>"><?php echo esc_html($cta); ?></a></p><?php } ?></div></div><?php $map=bt_launch_value('map_embed',''); if($map){ ?><div class="bt-map"><?php echo wp_kses($map,['iframe'=>['src'=>true,'width'=>true,'height'=>true,'style'=>true,'allowfullscreen'=>true,'loading'=>true,'referrerpolicy'=>true]]); ?></div><?php } ?></div></section></main>
<footer class="bt-footer"><div class="bt-wrap"><strong><?php bloginfo('name'); ?></strong><small>&copy; <?php echo esc_html(date('Y')); ?>. All rights reserved.</small></div></footer>
<?php get_footer(); ?>
