// Generated by the project's build command before Vercel packages this function.
// @ts-ignore The module does not exist until the build step runs.
import app from "../dist/server.mjs";

export default app;
